services:
  mysql:
    container_name: mysql
    build: ./sql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"

  php-apache:
    container_name: php-apache
    build: ./php
    env_file:
      - .env
    volumes:
      - ./src:/var/www/
      - ./.env:/var/www/.env
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - mysql

volumes:
    db_data: {}
